import type { Metadata } from "next";
import { LoadingProvider } from "@/context/LoadingContext";
import "./globals.css";
import Nav from "@/components/Nav";
import TransitionProvider from "@/context/TransitionContext";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en">
            <body className="">
                <LoadingProvider>
                    <TransitionProvider>
                        <Nav/>
                        <div>
                            {children}
                        </div>
                    </TransitionProvider>
                </LoadingProvider>
            </body>
        </html>
    );
}
