import type { Metadata } from "next";
import { LoadingProvider } from "@/context/LoadingContext";
import "./globals.css";
import TransitionProvider from "@/context/TransitionContext";
import Nav from "@/components/Nav";
import Cursor from "@/components/Cursor";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en" className="cursor-none">
            <body>
                <LoadingProvider>
                    <TransitionProvider>
                        {/* <Menu></Menu> */}
                        <div className=" absolute w-screen flex items-center justify-center h-32 magnet">
                            <Nav></Nav>
                        </div>


                        <div>
                            <Cursor></Cursor>
                            {children}
                        </div>
                    </TransitionProvider>
                </LoadingProvider>
            </body>
        </html>
    );
}
